[package]
name = "rust-programming-contest-solutions"
version = "0.1.0"
authors = ["kenkoooo <kenkou.n@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.7"
num-bigint = "0.3.0"
competitive-programming-rs = { path = "../competitive-programming-rs" }
